language: node_js
node_js:
  - "10"
  - "8"
  - "6"
sudo: false
script: "npm test"
env:
  global:
    NPM_AUTH_KEY: "12345"
jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: "bash ./scripts/deploy.sh"
      if: branch = master
